DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Friends;

DROP TABLE IF EXISTS Cities;

DROP TABLE IF EXISTS User_Current_Cities;

DROP TABLE IF EXISTS User_Hometown_Cities;

DROP TABLE IF EXISTS Messages;

DROP TABLE IF EXISTS Programs;

DROP TABLE IF EXISTS Education;

DROP TABLE IF EXISTS User_Events;

DROP TABLE IF EXISTS Participants;

DROP TABLE IF EXISTS Albums;

DROP TABLE IF EXISTS Photos;

DROP TABLE IF EXISTS Tags;

DROP TRIGGER IF EXISTS user_id_trigger;

DROP TRIGGER IF EXISTS Order_Friend_Pairs;

DROP SEQUENCE IF EXISTS user_seq;

DROP SEQUENCE IF EXISTS city_seq;

ALTER TABLE
    Photos DROP CONSTRAINT IF EXISTS fk_album;

ALTER TABLE
    Albums DROP CONSTRAINT IF EXISTS fk_cover_photo;