CREATE VIEW StudentPairs AS
SELECT DISTINCT e1.SID AS SID1, e2.SID AS SID2
FROM Enrollments e1
JOIN Enrollments e2 ON e1.CID = e2.CID AND e1.SID < e2.SID
LEFT JOIN Members m1 ON e1.SID = m1.SID
LEFT JOIN Members m2 ON e2.SID = m2.SID AND m1.PID = m2.PID
WHERE m1.PID IS NULL;
